backend:
  name: test-repo

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "test"
    label: "Test"
    files:
      - name: "hello"
        label: "Hello"
        file: "content/hello.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }