import type { Metadata } from "next";
import { Montserrat, Balthazar } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css"
import Footer from "@/components/footer";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["400", "500", "600", "900"],
});

const balthazar = Balthazar({
  subsets: ["latin"],
  variable: "--font-balthazar",
  weight: ["400"],
});

const josh_handwriting = localFont({
  src: "./fonts/josh_handwriting.woff2",
  variable: "--font-handwritten",
});

const basicform = localFont({
  src: "./fonts/basicform.woff2",
  variable: "--font-basicform",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`
          ${montserrat.variable}
          ${balthazar.variable}
          ${josh_handwriting.variable}
          ${basicform.variable}
        `}
      >
        {children}
        <Footer/>
      </body>
    </html>
  );
}
